### ISSUE TITLE
UE 4.18 Support

### ISSUE THREAD

**Issue by rlabrecque** [kitelightning/LivePP#1]
Hey ikrima,

The following is all that is needed to add 4.18 support:

In LPPExternalLib.Build.cs:
Old:
```
            RuntimeDependencies.Add(Path.Combine(BinariesPath(Target.Platform), string.Format("LPP_{0}.dll", archSuffix)));
            RuntimeDependencies.Add(Path.Combine(BinariesPath(Target.Platform), string.Format("LPP_{0}.exe", archSuffix)));
            RuntimeDependencies.Add(Path.Combine(BinariesPath(Target.Platform), "msdia140.dll"));
```
New:
```
            RuntimeDependencies.Add(new RuntimeDependency(Path.Combine(BinariesPath(Target.Platform), string.Format("LPP_{0}.dll", archSuffix))));
            RuntimeDependencies.Add(new RuntimeDependency(Path.Combine(BinariesPath(Target.Platform), string.Format("LPP_{0}.exe", archSuffix))));
            RuntimeDependencies.Add(new RuntimeDependency(Path.Combine(BinariesPath(Target.Platform), "msdia140.dll")));
```

Does this change work with 4.19/4.20?

**Comment by ikrima** [comment]
Hah! I need to opensource better. Just happenstance saw this so I think notifications are off.

Let me inspect

**Comment by ikrima** [comment]
Also definitely did not realize people were actively using this. I've been just pushing changes upstream without much thought. I'll try to make tags/branches

**Comment by ikrima** [comment]
Looks like no can do:
/// <param name="InRuntimeDependency">RuntimeDependency instance</param>
			[Obsolete("Constructing a RuntimeDependency object is deprecated. Call RuntimeDependencies.Add() with the path to the file to stage.")]

**Comment by rlabrecque** [comment]
Yeah, I don't care about this one anymore :) We're on 4.20+ now.
