### ISSUE TITLE
Some Question About This LivePP Plugin.

### ISSUE THREAD

**Issue by sunkui1993** [kitelightning/LivePP#5]
Hi,
I am very grateful to you for providing this plugin. I wanna ask some question about this . i know Live++ is in use by a lot of people or studios that use UE4 , and i am one of it . I have already downloaded this plugin. And I also have integrated it into UE4. but i do not know how to use it. I didn't find any tutorials on how to use it in UE4. Do i need to drag some blueprint to make it work ？Can you give me any help or suggest？ many thanks.

**Comment by ikrima** [comment]
Ah, sorry, just seeing these. Well, if you upgrade to 4.22, it's already integrated for you!
