### ISSUE TITLE
This Wrapper Is Probably Not Required Anymore

### ISSUE THREAD

**Issue by dyanikoglu** [kitelightning/LivePP#6]
Epic just made this commit inside 4.22 branch, and looks like it's their own implementation from the source code of Live++: https://github.com/EpicGames/UnrealEngine/commit/e1fe0cc030d004459316cc6c17debfc657b0c5a7

Edit: After some amount of testing, looks like it works good enough for an experimental version.

**Comment by ikrima** [comment]
Yup!
