### ISSUE TITLE
Having trouble with building plugin for UE4.20

### ISSUE THREAD

**Issue by AliElSaleh** [kitelightning/LivePP#7]
I'm on step 4 and having trouble building.
How do I build the plugin to get the UE4Editor-LivePP.lib file?

![LivePPBuildError](https://user-images.githubusercontent.com/19608222/55664267-65931000-5877-11e9-83f1-de50ba00c9b3.PNG)

**Comment by ikrima** [comment]
If you upgrade to 4.22, it'll already be integrated for you!
